[package]
name = "konnect"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kore = { path = "../kore/"}
kdata = { path = "../kdata/"}

rouille.workspace = true
serde.workspace = true