[package]
name = "kdata"
version.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
acc_personal = []

[dependencies]
krypto = { path = "../krypto/"}
serde.workspace = true
chrono.workspace = true