# Port to access the server
port = 7878
# Admin email address
admin_email = "admin@example.com"
# Kong server working directory, path should end with `/`
# defaults to ~/kong/
working_directory = "test-data/"
# Set to `true` if you want kong to create a database for accounts
# set to `false` if you don't want kong to create accounts db
# Database is created when `kong` starts up.
accounts = false
# Name of the authorization session cookie id
auth_cookie_name = "my_session"
# Path to static files, if not provided no static files will be served
# static_files_path = "www/"
# Node hostname
host = "my-host"
# Kong secret key
secret_key = "My super secret key" # Do not use in production
# Authentication/Login address (issue kpassport), defaults to `/auth`
# auth_route =  "/auth",