[package]
name = "kogs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kerror = { path = "../kerror/"}
serde.workspace = true
rusqlite.workspace = true