name: Rust

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone kontrollers
      run: git clone https://github.com/cipherlion/kong-kontrollers.git ./krates/kontrollers
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
