name: Rust

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create database test-data directory
      run: mkdir ./krates/kollection/test-data
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
